// File generated by flutterfire_cli.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX2Eem9NPnhFXlY4O_pUEqCy3d2Bb4CdE',
    appId: '1:297900356992:web:6f9b7b5a084662d5a6fd65',
    messagingSenderId: '297900356992',
    projectId: 'ict602app',
    authDomain: 'ict602app.firebaseapp.com',
    storageBucket: 'ict602app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX2Eem9NPnhFXlY4O_pUEqCy3d2Bb4CdE',
    appId: '1:297900356992:android:6f9b7b5a084662d5a6fd65',
    messagingSenderId: '297900356992',
    projectId: 'ict602app',
    storageBucket: 'ict602app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX2Eem9NPnhFXlY4O_pUEqCy3d2Bb4CdE',
    appId: '1:297900356992:ios:6f9b7b5a084662d5a6fd65',
    messagingSenderId: '297900356992',
    projectId: 'ict602app',
    storageBucket: 'ict602app.firebasestorage.app',
    iosBundleId: 'com.wanamirul.ict602app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX2Eem9NPnhFXlY4O_pUEqCy3d2Bb4CdE',
    appId: '1:297900356992:ios:6f9b7b5a084662d5a6fd65',
    messagingSenderId: '297900356992',
    projectId: 'ict602app',
    storageBucket: 'ict602app.firebasestorage.app',
    iosBundleId: 'com.wanamirul.ict602app',
  );
}
