// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-6ZPfPbDFqmEELzAg5VsBfpHeFQAkyAg',
    appId: '1:272124932330:web:7808287ae39a7142f56793',
    messagingSenderId: '272124932330',
    projectId: 'assignment2023509947',
    authDomain: 'assignment2023509947.firebaseapp.com',
    storageBucket: 'assignment2023509947.firebasestorage.app',
    measurementId: 'G-WBFWXXN59K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwK39T5SHehX64BFW2cnUQDYILVnJT1co',
    appId: '1:272124932330:android:0f893198ac8acbc2f56793',
    messagingSenderId: '272124932330',
    projectId: 'assignment2023509947',
    storageBucket: 'assignment2023509947.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxazvsBJie6C_oFS1XDko32zt5vxEGKAM',
    appId: '1:272124932330:ios:dfe4c9968cebbc29f56793',
    messagingSenderId: '272124932330',
    projectId: 'assignment2023509947',
    storageBucket: 'assignment2023509947.firebasestorage.app',
    iosClientId: '272124932330-5gh7j2t3k4uovr56vr2mc7366b8ohb4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment2023509947',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxazvsBJie6C_oFS1XDko32zt5vxEGKAM',
    appId: '1:272124932330:ios:dfe4c9968cebbc29f56793',
    messagingSenderId: '272124932330',
    projectId: 'assignment2023509947',
    storageBucket: 'assignment2023509947.firebasestorage.app',
    iosClientId: '272124932330-5gh7j2t3k4uovr56vr2mc7366b8ohb4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment2023509947',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-6ZPfPbDFqmEELzAg5VsBfpHeFQAkyAg',
    appId: '1:272124932330:web:9ad76ef413db6527f56793',
    messagingSenderId: '272124932330',
    projectId: 'assignment2023509947',
    authDomain: 'assignment2023509947.firebaseapp.com',
    storageBucket: 'assignment2023509947.firebasestorage.app',
    measurementId: 'G-EQ5P1XQL8P',
  );
}
