import 'package:assignment_2023509947/lecturerhomepage.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire CLI
import 'login_page.dart';
import 'adminhomepage.dart';
import 'studenthomepage.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget{
  const MyApp ({super.key});

@override
Widget build (BuildContext context){
  return MaterialApp(
    title: 'Subject Portal ICT602',
    theme: ThemeData(
      colorScheme: ColorScheme.fromSeed(seedColor:Colors.redAccent),
      useMaterial3: true,
    ),
    initialRoute: '/login',
    routes: {
    '/login': (context) => const LoginPage(),
    '/adminHome': (context) => const Adminhomepage(),
    '/lecturerHome': (context) => LecturerDashboard(),
    '/studentHome': (context)=> StudentDashboard(),
    },
  );
}
}